spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: password
  kafka:
    producer:
      bootstrap-servers: localhost:9092
kafka:
  topic: netflix-stream


  profiles:
    default: default
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


server:
  port: 7070


